var typed = new Typed(".autoinputhome", {
    strings: [
              "非我族类，其心必异",
              "犯我中华者，虽远必诛",
              "多行不义必自毙",
              "为中华民族之伟大复兴而奋斗！",
              "兵者，诡道也",
              "It'll be a silent spring.",
              "Die traitorous dogs!",
              "We will bury them!",
              "Rockets fueled and ready.",
              "It will soon be a wasteland. ",
              "I cast a deadly shadow. ",
              "They will roam in fear.",
              "I am prepared to die!",
              "Yes, comrade. ",
              "Helium mix optional.",
              "Target sighted.",
              "They're history.",
              "Nonbelivers!",
              "Let the bullets fly!",
              "Enemy locked.",
              "Never existed.",
            ],
    typeSpeed: 100,
    backSpeed: 50,
    loop: true,
});